version: '3.4'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: release_ping
      POSTGRES_PASSWORD: release_ping
  restore-writestore:
    image: leifg/postgres-s3-backup
    command: restore --skip-cleanup --overwrite --postgres-host postgres --postgres-port 5432 --postgres-user release_ping --postgres-password release_ping --postgres-db release_ping_eventstore --aws-s3-bucket leifio-database-backups --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - type: bind
        source: ./tmp
        target: /tmp
    depends_on:
      - postgres
  restore-readstore:
    image: leifg/postgres-s3-backup
    command: restore --skip-cleanup --overwrite --postgres-host postgres --postgres-port 5432 --postgres-user release_ping --postgres-password release_ping --postgres-db release_ping_readstore --aws-s3-bucket leifio-database-backups --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - type: bind
        source: ./tmp
        target: /tmp
    depends_on:
      - postgres
