version: 2
jobs:
  build:
    docker:
      - image: leifg/release_ping-base
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run:
          name: Get Dependencies
          command: mix deps.get
      - run:
          name: Compile
          command: mix compile
      - persist_to_workspace:
          root: /
          paths:
            - root/project
  test:
    docker:
      - image: leifg/release_ping-base
        environment:
          MIX_ENV: test
      - image: postgres
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Wait for Postgres to be running
          command: wait-for-it -h localhost -p 5432 && sleep 2
      - run:
          name: Create Write Store
          command: mix event_store.create
      - run:
          name: Create Read Store
          command: mix ecto.create
      - run:
          name: Migrate Database
          command: mix ecto.migrate
      - run:
          name: Test
          command: mix test
  deploy:
    docker:
      - image: leifg/release_ping-base
        environment:
          MIX_ENV: prod
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Get Dependencies
          command: mix deps.get
      - run:
          name: Semantic Release
          command: semantic-release -vf -slug leifg/release_ping -noci || true
      - run:
          name: Run Deployment
          command: deployment/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
