version: 2
jobs:
  build:
    docker:
      - image: leifg/release_ping-backend
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run:
          name: Get Dependencies
          command: mix deps.get
      - run:
          name: Compile
          command: mix compile
      - persist_to_workspace:
          root: /
          paths:
            - root/project
  lint:
    docker:
      - image: leifg/elixir:edge
        environment:
          MIX_ENV: test
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Check code to be formatted
          command: mix format --check-formatted --dry-run
  test:
    docker:
      - image: leifg/release_ping-backend
        environment:
          MIX_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: release_ping
          POSTGRES_PASSWORD: release_ping
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Wait for Postgres to be running
          command: wait-for-it -h localhost -p 5432 && sleep 3
      - run:
          name: Set Up Database
          command: bin/setup.sh
      - run:
          name: Test
          command: mix test
  deploy:
    docker:
      - image: leifg/release_ping-backend
        environment:
          MIX_ENV: prod
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Get Dependencies
          command: mix deps.get
      - run:
          name: Determine Version
          command: deployment/determine_release.sh
      - run:
          name: Run Deployment
          command: deployment/deploy.sh
      - run:
          name: Semantic Release
          command: semantic-release -vf -slug leifg/release_ping -noci || true

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
